title: Computer Vision for Geosciences
description: from classical methods to modern approaches using Deep Learning
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
github:
  is_project_page: false